# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Atompy.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_atompy_mainwindow(object):
    def setupUi(self, atompy_mainwindow):
        atompy_mainwindow.setObjectName("atompy_mainwindow")
        atompy_mainwindow.resize(1024, 800)
        atompy_mainwindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(atompy_mainwindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tab_CS = QtWidgets.QTabWidget(self.centralwidget)
        self.tab_CS.setStyleSheet("background-color: rgb(245, 245, 245);")
        self.tab_CS.setUsesScrollButtons(True)
        self.tab_CS.setObjectName("tab_CS")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab)
        self.tabWidget_2.setStyleSheet("background-color: rgb(245, 245, 245);")
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_CS_GA = QtWidgets.QWidget()
        self.tab_CS_GA.setObjectName("tab_CS_GA")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_CS_GA)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_show_dir_cs = QtWidgets.QLabel(self.tab_CS_GA)
        self.lbl_show_dir_cs.setText("")
        self.lbl_show_dir_cs.setObjectName("lbl_show_dir_cs")
        self.verticalLayout.addWidget(self.lbl_show_dir_cs)
        self.gridLayout_4.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.gridLayout_18 = QtWidgets.QGridLayout()
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.label = QtWidgets.QLabel(self.tab_CS_GA)
        self.label.setStyleSheet("font: 12pt \"Ubuntu\";\n"
"color: rgb(0, 0, 0);")
        self.label.setObjectName("label")
        self.gridLayout_18.addWidget(self.label, 0, 0, 1, 1)
        self.progbar = QtWidgets.QProgressBar(self.tab_CS_GA)
        self.progbar.setHidden(True)
        self.progbar.setEnabled(True)
        self.progbar.setToolTip("")
        self.progbar.setStatusTip("")
        self.progbar.setWhatsThis("")
        self.progbar.setAccessibleName("")
        self.progbar.setProperty("value", 0)
        self.progbar.setTextVisible(True)
        self.progbar.setInvertedAppearance(False)
        self.progbar.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progbar.setObjectName("progbar")
        self.gridLayout_18.addWidget(self.progbar, 0, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_18, 1, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lbl_score_info_3 = QtWidgets.QLabel(self.tab_CS_GA)
        self.lbl_score_info_3.setObjectName("lbl_score_info_3")
        self.gridLayout_3.addWidget(self.lbl_score_info_3, 4, 3, 1, 1)
        self.lbl_converge_inf = QtWidgets.QLabel(self.tab_CS_GA)
        self.lbl_converge_inf.setObjectName("lbl_converge_inf")
        self.gridLayout_3.addWidget(self.lbl_converge_inf, 3, 3, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 0, 7, 1, 1)
        self.lbl_mut = QtWidgets.QLabel(self.tab_CS_GA)
        self.lbl_mut.setStyleSheet("font: 12pt \"Ubuntu\";\n"
"color: rgb(0, 0, 0);")
        self.lbl_mut.setObjectName("lbl_mut")
        self.gridLayout_3.addWidget(self.lbl_mut, 2, 0, 1, 1)
        self.lbl_nconf_info_3 = QtWidgets.QLabel(self.tab_CS_GA)
        self.lbl_nconf_info_3.setObjectName("lbl_nconf_info_3")
        self.gridLayout_3.addWidget(self.lbl_nconf_info_3, 0, 3, 1, 1)
        self.txt_child = QtWidgets.QLineEdit(self.tab_CS_GA)
        self.txt_child.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_child.setObjectName("txt_child")
        self.gridLayout_3.addWidget(self.txt_child, 1, 1, 1, 1)
        self.lbl_score_1 = QtWidgets.QLabel(self.tab_CS_GA)
        self.lbl_score_1.setStyleSheet("font: 12pt \"Ubuntu\";\n"
"color: rgb(0, 0, 0);")
        self.lbl_score_1.setObjectName("lbl_score_1")
        self.gridLayout_3.addWidget(self.lbl_score_1, 4, 0, 1, 1)
        self.lbl_mutability_info_3 = QtWidgets.QLabel(self.tab_CS_GA)
        self.lbl_mutability_info_3.setObjectName("lbl_mutability_info_3")
        self.gridLayout_3.addWidget(self.lbl_mutability_info_3, 2, 3, 1, 1)
        self.txt_mut = QtWidgets.QLineEdit(self.tab_CS_GA)
        self.txt_mut.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_mut.setObjectName("txt_mut")
        self.gridLayout_3.addWidget(self.txt_mut, 2, 1, 1, 1)
        self.txt_ncon = QtWidgets.QLineEdit(self.tab_CS_GA)
        self.txt_ncon.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_ncon.setText("")
        self.txt_ncon.setObjectName("txt_ncon")
        self.gridLayout_3.addWidget(self.txt_ncon, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 0, 6, 1, 1)
        self.lbl_children_info_3 = QtWidgets.QLabel(self.tab_CS_GA)
        self.lbl_children_info_3.setObjectName("lbl_children_info_3")
        self.gridLayout_3.addWidget(self.lbl_children_info_3, 1, 3, 1, 1)
        self.lbl_conv = QtWidgets.QLabel(self.tab_CS_GA)
        self.lbl_conv.setStyleSheet("font: 12pt \"Ubuntu\";\n"
"color: rgb(0, 0, 0);")
        self.lbl_conv.setObjectName("lbl_conv")
        self.gridLayout_3.addWidget(self.lbl_conv, 3, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 0, 4, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem3, 0, 5, 1, 1)
        self.lbl_child = QtWidgets.QLabel(self.tab_CS_GA)
        self.lbl_child.setStyleSheet("font: 12pt \"Ubuntu\";\n"
"color: rgb(0, 0, 0);")
        self.lbl_child.setObjectName("lbl_child")
        self.gridLayout_3.addWidget(self.lbl_child, 1, 0, 1, 1)
        self.txt_conv = QtWidgets.QLineEdit(self.tab_CS_GA)
        self.txt_conv.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_conv.setObjectName("txt_conv")
        self.gridLayout_3.addWidget(self.txt_conv, 3, 1, 1, 1)
        self.lbl_ncon = QtWidgets.QLabel(self.tab_CS_GA)
        self.lbl_ncon.setStyleSheet("font: 12pt \"Ubuntu\";\n"
"color: rgb(0, 0, 0);")
        self.lbl_ncon.setObjectName("lbl_ncon")
        self.gridLayout_3.addWidget(self.lbl_ncon, 0, 0, 1, 1)
        self.txt_scor = QtWidgets.QLineEdit(self.tab_CS_GA)
        self.txt_scor.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_scor.setObjectName("txt_scor")
        self.gridLayout_3.addWidget(self.txt_scor, 4, 1, 1, 1)
        self.lbl_ffe_info = QtWidgets.QLabel(self.tab_CS_GA)
        self.lbl_ffe_info.setStyleSheet("font: 12pt \"Ubuntu\";\n"
"color: rgb(0, 0, 0);")
        self.lbl_ffe_info.setObjectName("lbl_ffe_info")
        self.gridLayout_3.addWidget(self.lbl_ffe_info, 5, 0, 1, 1)
        self.cbox_energyfield = QtWidgets.QComboBox(self.tab_CS_GA)
        self.cbox_energyfield.setStyleSheet("")
        self.cbox_energyfield.setObjectName("cbox_energyfield")
        self.cbox_energyfield.addItem("")
        self.cbox_energyfield.addItem("")
        self.cbox_energyfield.addItem("")
        self.cbox_energyfield.addItem("")
        self.cbox_energyfield.addItem("")
        self.gridLayout_3.addWidget(self.cbox_energyfield, 5, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 2, 0, 1, 1)
        self.gridLayout_36 = QtWidgets.QGridLayout()
        self.gridLayout_36.setObjectName("gridLayout_36")
        self.label_7 = QtWidgets.QLabel(self.tab_CS_GA)
        self.label_7.setStyleSheet("font: 12pt \"Ubuntu\";\n"
"color: rgb(0, 0, 0);")
        self.label_7.setObjectName("label_7")
        self.gridLayout_36.addWidget(self.label_7, 0, 18, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_36.addItem(spacerItem4, 1, 5, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_36.addItem(spacerItem5, 1, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_36.addItem(spacerItem6, 1, 12, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_36.addItem(spacerItem7, 1, 14, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_36.addItem(spacerItem8, 1, 16, 1, 1)
        self.btn_energy_GA_run = QtWidgets.QPushButton(self.tab_CS_GA)
        self.btn_energy_GA_run.setObjectName("btn_energy_GA_run")
        self.gridLayout_36.addWidget(self.btn_energy_GA_run, 1, 18, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_36.addItem(spacerItem9, 0, 6, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_36.addItem(spacerItem10, 1, 8, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_36.addItem(spacerItem11, 1, 13, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_36.addItem(spacerItem12, 1, 19, 1, 1)
        self.btn_GA_run = QtWidgets.QPushButton(self.tab_CS_GA)
        self.btn_GA_run.setObjectName("btn_GA_run")
        self.gridLayout_36.addWidget(self.btn_GA_run, 1, 11, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_36.addItem(spacerItem13, 1, 15, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_36.addItem(spacerItem14, 1, 21, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.tab_CS_GA)
        self.label_4.setStyleSheet("font: 12pt \"Ubuntu\";\n"
"color: rgb(0, 0, 0);")
        self.label_4.setObjectName("label_4")
        self.gridLayout_36.addWidget(self.label_4, 1, 3, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_36.addItem(spacerItem15, 1, 9, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_36.addItem(spacerItem16, 1, 20, 1, 1)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_36.addItem(spacerItem17, 1, 17, 1, 1)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_36.addItem(spacerItem18, 1, 1, 1, 1)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_36.addItem(spacerItem19, 1, 4, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tab_CS_GA)
        self.label_2.setStyleSheet("font: 12pt \"Ubuntu\";\n"
"color: rgb(0, 0, 0);")
        self.label_2.setObjectName("label_2")
        self.gridLayout_36.addWidget(self.label_2, 0, 11, 1, 1)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_36.addItem(spacerItem20, 1, 7, 1, 1)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_36.addItem(spacerItem21, 1, 2, 1, 1)
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_36.addItem(spacerItem22, 1, 10, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_36, 3, 0, 1, 1)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.txt_log_show = QtWidgets.QTextEdit(self.tab_CS_GA)
        self.txt_log_show.setObjectName("txt_log_show")
        self.horizontalLayout_11.addWidget(self.txt_log_show)
        self.txt_conformer_show = QtWidgets.QTextEdit(self.tab_CS_GA)
        self.txt_conformer_show.setObjectName("txt_conformer_show")
        self.horizontalLayout_11.addWidget(self.txt_conformer_show)
        self.txt_energy_show = QtWidgets.QTextEdit(self.tab_CS_GA)
        self.txt_energy_show.setObjectName("txt_energy_show")
        self.horizontalLayout_11.addWidget(self.txt_energy_show)
        self.gridLayout_4.addLayout(self.horizontalLayout_11, 4, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab_CS_GA, "")
        self.tab_CS_FF = QtWidgets.QWidget()
        self.tab_CS_FF.setObjectName("tab_CS_FF")
        self.tabWidget_2.addTab(self.tab_CS_FF, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        spacerItem23 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem23, 0, 1, 1, 1)
        spacerItem24 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem24, 1, 0, 1, 1)
        spacerItem25 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem25, 1, 3, 1, 1)
        self.txt_tempboltz = QtWidgets.QLineEdit(self.tab_4)
        self.txt_tempboltz.setObjectName("txt_tempboltz")
        self.gridLayout_6.addWidget(self.txt_tempboltz, 1, 2, 1, 1)
        self.lbl_nconfboltz = QtWidgets.QLabel(self.tab_4)
        self.lbl_nconfboltz.setObjectName("lbl_nconfboltz")
        self.gridLayout_6.addWidget(self.lbl_nconfboltz, 2, 1, 1, 1)
        self.txt_nconfboltz = QtWidgets.QLineEdit(self.tab_4)
        self.txt_nconfboltz.setObjectName("txt_nconfboltz")
        self.gridLayout_6.addWidget(self.txt_nconfboltz, 2, 2, 1, 1)
        self.lbl_tempboltz = QtWidgets.QLabel(self.tab_4)
        self.lbl_tempboltz.setObjectName("lbl_tempboltz")
        self.gridLayout_6.addWidget(self.lbl_tempboltz, 1, 1, 1, 1)
        spacerItem26 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem26, 5, 1, 1, 1)
        self.btn_gerar_tables = QtWidgets.QPushButton(self.tab_4)
        self.btn_gerar_tables.setObjectName("btn_gerar_tables")
        self.gridLayout_6.addWidget(self.btn_gerar_tables, 3, 2, 1, 1)
        self.btn_run_boltz = QtWidgets.QPushButton(self.tab_4)
        self.btn_run_boltz.setObjectName("btn_run_boltz")
        self.gridLayout_6.addWidget(self.btn_run_boltz, 3, 3, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        self.grid_tables = QtWidgets.QGridLayout()
        self.grid_tables.setObjectName("grid_tables")
        self.tables = QtWidgets.QTableWidget(self.tab_4)
        self.tables.setObjectName("tables")
        self.tables.setColumnCount(0)
        self.tables.setRowCount(0)
        self.grid_tables.addWidget(self.tables, 0, 0, 1, 1)
        self.gridLayout_7.addLayout(self.grid_tables, 0, 1, 1, 1)
        self.tabWidget_2.addTab(self.tab_4, "")
        self.gridLayout_2.addWidget(self.tabWidget_2, 0, 0, 1, 1)
        self.tab_CS.addTab(self.tab, "")
        self.tab_ssnmr = QtWidgets.QWidget()
        self.tab_ssnmr.setObjectName("tab_ssnmr")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.tab_ssnmr)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lbl_show_dir_cs_2 = QtWidgets.QLabel(self.tab_ssnmr)
        self.lbl_show_dir_cs_2.setText("")
        self.lbl_show_dir_cs_2.setObjectName("lbl_show_dir_cs_2")
        self.verticalLayout_2.addWidget(self.lbl_show_dir_cs_2)
        self.gridLayout_11.addLayout(self.verticalLayout_2, 0, 0, 1, 2)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.ln6_kgrid = QtWidgets.QLineEdit(self.tab_ssnmr)
        self.ln6_kgrid.setObjectName("ln6_kgrid")
        self.gridLayout_5.addWidget(self.ln6_kgrid, 2, 6, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.tab_ssnmr)
        self.label_5.setStyleSheet("font: 12pt \"Ubuntu\";\n"
"color: rgb(0, 0, 0);")
        self.label_5.setObjectName("label_5")
        self.gridLayout_5.addWidget(self.label_5, 2, 0, 1, 1)
        self.ln4_kgrid = QtWidgets.QLineEdit(self.tab_ssnmr)
        self.ln4_kgrid.setObjectName("ln4_kgrid")
        self.gridLayout_5.addWidget(self.ln4_kgrid, 2, 4, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.tab_ssnmr)
        self.label_3.setStyleSheet("font: 12pt \"Ubuntu\";\n"
"color: rgb(0, 0, 0);")
        self.label_3.setObjectName("label_3")
        self.gridLayout_5.addWidget(self.label_3, 1, 0, 1, 1)
        self.ln1_kgrid = QtWidgets.QLineEdit(self.tab_ssnmr)
        self.ln1_kgrid.setObjectName("ln1_kgrid")
        self.gridLayout_5.addWidget(self.ln1_kgrid, 2, 1, 1, 1)
        self.ln2_kgrid = QtWidgets.QLineEdit(self.tab_ssnmr)
        self.ln2_kgrid.setObjectName("ln2_kgrid")
        self.gridLayout_5.addWidget(self.ln2_kgrid, 2, 2, 1, 1)
        self.ln5_kgrid = QtWidgets.QLineEdit(self.tab_ssnmr)
        self.ln5_kgrid.setObjectName("ln5_kgrid")
        self.gridLayout_5.addWidget(self.ln5_kgrid, 2, 5, 1, 1)
        spacerItem27 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem27, 2, 12, 1, 1)
        spacerItem28 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem28, 2, 8, 1, 1)
        self.ln_ibrav = QtWidgets.QLineEdit(self.tab_ssnmr)
        self.ln_ibrav.setObjectName("ln_ibrav")
        self.gridLayout_5.addWidget(self.ln_ibrav, 0, 1, 1, 1)
        spacerItem29 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem29, 2, 11, 1, 1)
        self.ln_cutoff = QtWidgets.QLineEdit(self.tab_ssnmr)
        self.ln_cutoff.setObjectName("ln_cutoff")
        self.gridLayout_5.addWidget(self.ln_cutoff, 1, 1, 1, 1)
        self.ln3_kgrid = QtWidgets.QLineEdit(self.tab_ssnmr)
        self.ln3_kgrid.setObjectName("ln3_kgrid")
        self.gridLayout_5.addWidget(self.ln3_kgrid, 2, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.tab_ssnmr)
        self.label_6.setStyleSheet("font: 12pt \"Ubuntu\";\n"
"color: rgb(0, 0, 0);")
        self.label_6.setObjectName("label_6")
        self.gridLayout_5.addWidget(self.label_6, 0, 0, 1, 1)
        spacerItem30 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem30, 2, 10, 1, 1)
        spacerItem31 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem31, 2, 9, 1, 1)
        spacerItem32 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem32, 2, 7, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_5, 1, 0, 1, 1)
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_9 = QtWidgets.QLabel(self.tab_ssnmr)
        self.label_9.setStyleSheet("font: 12pt \"Ubuntu\";\n"
"color: rgb(0, 0, 0);")
        self.label_9.setObjectName("label_9")
        self.gridLayout_10.addWidget(self.label_9, 0, 0, 1, 1)
        self.cbox_pseudop = QtWidgets.QComboBox(self.tab_ssnmr)
        self.cbox_pseudop.setObjectName("cbox_pseudop")
        self.cbox_pseudop.addItem("")
        self.cbox_pseudop.setItemText(0, "New-Gipaw")
        self.cbox_pseudop.addItem("")
        self.gridLayout_10.addWidget(self.cbox_pseudop, 1, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.tab_ssnmr)
        self.label_8.setStyleSheet("font: 12pt \"Ubuntu\";\n"
"color: rgb(0, 0, 0);")
        self.label_8.setObjectName("label_8")
        self.gridLayout_10.addWidget(self.label_8, 1, 0, 1, 1)
        self.cbox_diagonalization = QtWidgets.QComboBox(self.tab_ssnmr)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(245, 245, 245))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(245, 245, 245))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(245, 245, 245))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(245, 245, 245))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(245, 245, 245))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(245, 245, 245))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(245, 245, 245))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(245, 245, 245))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(245, 245, 245))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.cbox_diagonalization.setPalette(palette)
        self.cbox_diagonalization.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.cbox_diagonalization.setMouseTracking(False)
        self.cbox_diagonalization.setEditable(False)
        self.cbox_diagonalization.setDuplicatesEnabled(False)
        self.cbox_diagonalization.setObjectName("cbox_diagonalization")
        self.cbox_diagonalization.addItem("")
        self.cbox_diagonalization.addItem("")
        self.gridLayout_10.addWidget(self.cbox_diagonalization, 0, 1, 1, 1)
        spacerItem33 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem33, 0, 2, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_10, 2, 0, 1, 1)
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.txt_pwin = QtWidgets.QTextEdit(self.tab_ssnmr)
        self.txt_pwin.setObjectName("txt_pwin")
        self.gridLayout_8.addWidget(self.txt_pwin, 1, 0, 1, 1)
        self.btn_pwout = QtWidgets.QPushButton(self.tab_ssnmr)
        self.btn_pwout.setObjectName("btn_pwout")
        self.gridLayout_8.addWidget(self.btn_pwout, 0, 1, 1, 1)
        self.btn_pwin = QtWidgets.QPushButton(self.tab_ssnmr)
        self.btn_pwin.setObjectName("btn_pwin")
        self.gridLayout_8.addWidget(self.btn_pwin, 0, 0, 1, 1)
        self.txt_gipaw = QtWidgets.QTextEdit(self.tab_ssnmr)
        self.txt_gipaw.setObjectName("txt_gipaw")
        self.gridLayout_8.addWidget(self.txt_gipaw, 1, 2, 1, 1)
        self.btn_gipaw = QtWidgets.QPushButton(self.tab_ssnmr)
        self.btn_gipaw.setObjectName("btn_gipaw")
        self.gridLayout_8.addWidget(self.btn_gipaw, 0, 2, 1, 1)
        self.txt_pwout = QtWidgets.QTextEdit(self.tab_ssnmr)
        self.txt_pwout.setObjectName("txt_pwout")
        self.gridLayout_8.addWidget(self.txt_pwout, 1, 1, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_8, 3, 0, 1, 1)
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.btn_nmrgraph = QtWidgets.QPushButton(self.tab_ssnmr)
        self.btn_nmrgraph.setObjectName("btn_nmrgraph")
        self.gridLayout_9.addWidget(self.btn_nmrgraph, 1, 0, 1, 1)
        self.btn_scfgraph = QtWidgets.QPushButton(self.tab_ssnmr)
        self.btn_scfgraph.setObjectName("btn_scfgraph")
        self.gridLayout_9.addWidget(self.btn_scfgraph, 0, 0, 1, 1)
        spacerItem34 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem34, 3, 0, 1, 1)
        spacerItem35 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem35, 0, 1, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.tab_ssnmr)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_9.addWidget(self.pushButton_6, 2, 0, 1, 1)
        spacerItem36 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem36, 2, 2, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.tab_ssnmr)
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_9.addWidget(self.pushButton_7, 2, 1, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_9, 3, 1, 1, 1)
        self.tab_CS.addTab(self.tab_ssnmr, "")
        self.gridLayout.addWidget(self.tab_CS, 0, 0, 1, 1)
        atompy_mainwindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(atompy_mainwindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 23))
        self.menubar.setObjectName("menubar")
        self.menuFIle = QtWidgets.QMenu(self.menubar)
        self.menuFIle.setObjectName("menuFIle")
        self.menuExport = QtWidgets.QMenu(self.menuFIle)
        self.menuExport.setObjectName("menuExport")
        self.menuSave_as = QtWidgets.QMenu(self.menuFIle)
        self.menuSave_as.setObjectName("menuSave_as")
        self.menuCalc = QtWidgets.QMenu(self.menubar)
        self.menuCalc.setObjectName("menuCalc")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        atompy_mainwindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(atompy_mainwindow)
        self.statusbar.setObjectName("statusbar")
        atompy_mainwindow.setStatusBar(self.statusbar)
        self.menu_open = QtWidgets.QAction(atompy_mainwindow)
        self.menu_open.setObjectName("menu_open")
        self.menu_export_mol = QtWidgets.QAction(atompy_mainwindow)
        self.menu_export_mol.setObjectName("menu_export_mol")
        self.menu_export_mol2 = QtWidgets.QAction(atompy_mainwindow)
        self.menu_export_mol2.setObjectName("menu_export_mol2")
        self.menu_export_com = QtWidgets.QAction(atompy_mainwindow)
        self.menu_export_com.setObjectName("menu_export_com")
        self.menu_export_xyz = QtWidgets.QAction(atompy_mainwindow)
        self.menu_export_xyz.setObjectName("menu_export_xyz")
        self.menu_save = QtWidgets.QAction(atompy_mainwindow)
        self.menu_save.setObjectName("menu_save")
        self.menu_save_energy = QtWidgets.QAction(atompy_mainwindow)
        self.menu_save_energy.setObjectName("menu_save_energy")
        self.menu_save_conformers = QtWidgets.QAction(atompy_mainwindow)
        self.menu_save_conformers.setObjectName("menu_save_conformers")
        self.menu_save_PWscf_input = QtWidgets.QAction(atompy_mainwindow)
        self.menu_save_PWscf_input.setObjectName("menu_save_PWscf_input")
        self.menu_save_PWscf_output = QtWidgets.QAction(atompy_mainwindow)
        self.menu_save_PWscf_output.setObjectName("menu_save_PWscf_output")
        self.menu_save_gipaw_input = QtWidgets.QAction(atompy_mainwindow)
        self.menu_save_gipaw_input.setObjectName("menu_save_gipaw_input")
        self.menu_save_gipaw_output = QtWidgets.QAction(atompy_mainwindow)
        self.menu_save_gipaw_output.setObjectName("menu_save_gipaw_output")
        self.menu_quit = QtWidgets.QAction(atompy_mainwindow)
        self.menu_quit.setObjectName("menu_quit")
        self.run_cs_ga = QtWidgets.QAction(atompy_mainwindow)
        self.run_cs_ga.setObjectName("run_cs_ga")
        self.run_cs_ff = QtWidgets.QAction(atompy_mainwindow)
        self.run_cs_ff.setObjectName("run_cs_ff")
        self.run_pwscf_input = QtWidgets.QAction(atompy_mainwindow)
        self.run_pwscf_input.setObjectName("run_pwscf_input")
        self.run_pwscf_output = QtWidgets.QAction(atompy_mainwindow)
        self.run_pwscf_output.setObjectName("run_pwscf_output")
        self.run_pwscf_gipaw = QtWidgets.QAction(atompy_mainwindow)
        self.run_pwscf_gipaw.setObjectName("run_pwscf_gipaw")
        self.menu_tutorials = QtWidgets.QAction(atompy_mainwindow)
        self.menu_tutorials.setObjectName("menu_tutorials")
        self.menu_about = QtWidgets.QAction(atompy_mainwindow)
        self.menu_about.setObjectName("menu_about")
        self.menuExport.addAction(self.menu_export_mol)
        self.menuExport.addAction(self.menu_export_mol2)
        self.menuExport.addAction(self.menu_export_com)
        self.menuExport.addAction(self.menu_export_xyz)
        self.menuSave_as.addAction(self.menu_save_energy)
        self.menuSave_as.addAction(self.menu_save_conformers)
        self.menuSave_as.addAction(self.menu_save_PWscf_input)
        self.menuSave_as.addAction(self.menu_save_PWscf_output)
        self.menuSave_as.addAction(self.menu_save_gipaw_input)
        self.menuSave_as.addAction(self.menu_save_gipaw_output)
        self.menuFIle.addAction(self.menu_open)
        self.menuFIle.addAction(self.menu_save)
        self.menuFIle.addAction(self.menuSave_as.menuAction())
        self.menuFIle.addAction(self.menuExport.menuAction())
        self.menuFIle.addSeparator()
        self.menuFIle.addAction(self.menu_quit)
        self.menuCalc.addAction(self.run_cs_ga)
        self.menuCalc.addAction(self.run_cs_ff)
        self.menuCalc.addAction(self.run_pwscf_input)
        self.menuCalc.addAction(self.run_pwscf_output)
        self.menuCalc.addAction(self.run_pwscf_gipaw)
        self.menuHelp.addAction(self.menu_tutorials)
        self.menuAbout.addAction(self.menu_about)
        self.menubar.addAction(self.menuFIle.menuAction())
        self.menubar.addAction(self.menuCalc.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(atompy_mainwindow)
        self.tab_CS.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        self.cbox_diagonalization.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(atompy_mainwindow)

    def retranslateUi(self, atompy_mainwindow):
        _translate = QtCore.QCoreApplication.translate
        atompy_mainwindow.setWindowTitle(_translate("atompy_mainwindow", "Atompy"))
        self.label.setText(_translate("atompy_mainwindow", "Parameters"))
        self.lbl_score_info_3.setText(_translate("atompy_mainwindow", " Scoring function [rmsd or energy] (default  =  rmsd)"))
        self.lbl_converge_inf.setText(_translate("atompy_mainwindow", " Number of identical generations before convergence is reached"))
        self.lbl_mut.setText(_translate("atompy_mainwindow", "Mutability:"))
        self.lbl_nconf_info_3.setText(_translate("atompy_mainwindow", " Number of conformers to generate"))
        self.lbl_score_1.setText(_translate("atompy_mainwindow", "Score:"))
        self.lbl_mutability_info_3.setText(_translate("atompy_mainwindow", " Mutation frequency (default  =  5)"))
        self.lbl_children_info_3.setText(_translate("atompy_mainwindow", " Number of chldren to generate for each parent (default = 5)"))
        self.lbl_conv.setText(_translate("atompy_mainwindow", "Converge:"))
        self.lbl_child.setText(_translate("atompy_mainwindow", "Children :"))
        self.lbl_ncon.setText(_translate("atompy_mainwindow", "Nconf:"))
        self.lbl_ffe_info.setText(_translate("atompy_mainwindow", "Force Field for Energy:"))
        self.cbox_energyfield.setItemText(0, _translate("atompy_mainwindow", "UFF"))
        self.cbox_energyfield.setItemText(1, _translate("atompy_mainwindow", "MMFF94"))
        self.cbox_energyfield.setItemText(2, _translate("atompy_mainwindow", "MMFF94s"))
        self.cbox_energyfield.setItemText(3, _translate("atompy_mainwindow", "Ghemical"))
        self.cbox_energyfield.setItemText(4, _translate("atompy_mainwindow", "GAFF"))
        self.label_7.setText(_translate("atompy_mainwindow", "    Energy"))
        self.btn_energy_GA_run.setText(_translate("atompy_mainwindow", "Calc"))
        self.btn_GA_run.setText(_translate("atompy_mainwindow", "Calc"))
        self.label_4.setText(_translate("atompy_mainwindow", "Log"))
        self.label_2.setText(_translate("atompy_mainwindow", "Conformers"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_CS_GA), _translate("atompy_mainwindow", "Genetic Algorithm"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_CS_FF), _translate("atompy_mainwindow", "Force Field"))
        self.lbl_nconfboltz.setText(_translate("atompy_mainwindow", "Type number of conformations:"))
        self.lbl_tempboltz.setText(_translate("atompy_mainwindow", "Type temperature in K:"))
        self.btn_gerar_tables.setText(_translate("atompy_mainwindow", "OK"))
        self.btn_run_boltz.setText(_translate("atompy_mainwindow", "Run"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("atompy_mainwindow", "Boltzmann Distribution"))
        self.tab_CS.setTabText(self.tab_CS.indexOf(self.tab), _translate("atompy_mainwindow", "Conformer Searching"))
        self.label_5.setText(_translate("atompy_mainwindow", "Kgrid:"))
        self.label_3.setText(_translate("atompy_mainwindow", "Cutoff:"))
        self.label_6.setText(_translate("atompy_mainwindow", "Ibrave:"))
        self.label_9.setText(_translate("atompy_mainwindow", "Diagonalization:"))
        self.cbox_pseudop.setItemText(1, _translate("atompy_mainwindow", "Ultrasoft"))
        self.label_8.setText(_translate("atompy_mainwindow", "Pseudo-Potential:"))
        self.cbox_diagonalization.setItemText(0, _translate("atompy_mainwindow", "David"))
        self.cbox_diagonalization.setItemText(1, _translate("atompy_mainwindow", "Cg"))
        self.txt_pwin.setHtml(_translate("atompy_mainwindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.btn_pwout.setText(_translate("atompy_mainwindow", "PWscf-output"))
        self.btn_pwin.setText(_translate("atompy_mainwindow", "PWscf-input"))
        self.btn_gipaw.setText(_translate("atompy_mainwindow", "Gipaw"))
        self.btn_nmrgraph.setText(_translate("atompy_mainwindow", "NMR_graph"))
        self.btn_scfgraph.setText(_translate("atompy_mainwindow", "SCF_graph"))
        self.pushButton_6.setText(_translate("atompy_mainwindow", "Func_futura"))
        self.pushButton_7.setText(_translate("atompy_mainwindow", "Func_futura2"))
        self.tab_CS.setTabText(self.tab_CS.indexOf(self.tab_ssnmr), _translate("atompy_mainwindow", "ss-NMR"))
        self.menuFIle.setTitle(_translate("atompy_mainwindow", "File"))
        self.menuExport.setTitle(_translate("atompy_mainwindow", "Export"))
        self.menuSave_as.setTitle(_translate("atompy_mainwindow", "Save as"))
        self.menuCalc.setTitle(_translate("atompy_mainwindow", "Calc"))
        self.menuHelp.setTitle(_translate("atompy_mainwindow", "Help"))
        self.menuAbout.setTitle(_translate("atompy_mainwindow", "About"))
        self.menu_open.setText(_translate("atompy_mainwindow", "Open"))
        self.menu_open.setShortcut(_translate("atompy_mainwindow", "Ctrl+O"))
        self.menu_export_mol.setText(_translate("atompy_mainwindow", "as MOL"))
        self.menu_export_mol2.setText(_translate("atompy_mainwindow", "as MOL2"))
        self.menu_export_com.setText(_translate("atompy_mainwindow", "as COM"))
        self.menu_export_xyz.setText(_translate("atompy_mainwindow", "as XYZ"))
        self.menu_save.setText(_translate("atompy_mainwindow", "Save"))
        self.menu_save.setShortcut(_translate("atompy_mainwindow", "Ctrl+S"))
        self.menu_save_energy.setText(_translate("atompy_mainwindow", "Save Energy"))
        self.menu_save_conformers.setText(_translate("atompy_mainwindow", "Save Conformers"))
        self.menu_save_PWscf_input.setText(_translate("atompy_mainwindow", "Save PWscf input"))
        self.menu_save_PWscf_output.setText(_translate("atompy_mainwindow", "Save PWscf output"))
        self.menu_save_gipaw_input.setText(_translate("atompy_mainwindow", "Save Gipaw input"))
        self.menu_save_gipaw_output.setText(_translate("atompy_mainwindow", "Save Gipaw output"))
        self.menu_quit.setText(_translate("atompy_mainwindow", "Quit"))
        self.menu_quit.setShortcut(_translate("atompy_mainwindow", "Ctrl+Q"))
        self.run_cs_ga.setText(_translate("atompy_mainwindow", "Run Conformer searching(GA)"))
        self.run_cs_ff.setText(_translate("atompy_mainwindow", "Run Conformer searching(FF)"))
        self.run_pwscf_input.setText(_translate("atompy_mainwindow", "Run Pwscf Input"))
        self.run_pwscf_output.setText(_translate("atompy_mainwindow", "Run Pwscf Output"))
        self.run_pwscf_gipaw.setText(_translate("atompy_mainwindow", "Run Pwscf Gipaw"))
        self.menu_tutorials.setText(_translate("atompy_mainwindow", "Tutorials"))
        self.menu_about.setText(_translate("atompy_mainwindow", "Atompy"))

