# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'spyn.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_spyn_mainwindow(object):
    def setupUi(self, spyn_mainwindow):
        spyn_mainwindow.setObjectName("spyn_mainwindow")
        spyn_mainwindow.resize(1152, 864)
        spyn_mainwindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(spyn_mainwindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tab_CS = QtWidgets.QTabWidget(self.centralwidget)
        self.tab_CS.setStyleSheet("background-color: rgb(245, 245, 245);")
        self.tab_CS.setUsesScrollButtons(True)
        self.tab_CS.setObjectName("tab_CS")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab)
        self.tabWidget_2.setStyleSheet("background-color: rgb(245, 245, 245);")
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_CS_GA = QtWidgets.QWidget()
        self.tab_CS_GA.setObjectName("tab_CS_GA")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_CS_GA)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_show_dir_cs = QtWidgets.QLabel(self.tab_CS_GA)
        self.lbl_show_dir_cs.setText("")
        self.lbl_show_dir_cs.setObjectName("lbl_show_dir_cs")
        self.verticalLayout.addWidget(self.lbl_show_dir_cs)
        self.gridLayout_4.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.gridLayout_18 = QtWidgets.QGridLayout()
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.label = QtWidgets.QLabel(self.tab_CS_GA)
        self.label.setStyleSheet("font: 12pt \"Ubuntu\";\n"
"color: rgb(0, 0, 0);")
        self.label.setObjectName("label")
        self.gridLayout_18.addWidget(self.label, 0, 0, 1, 1)
        self.progbar = QtWidgets.QProgressBar(self.tab_CS_GA)
        self.progbar.setEnabled(True)
        self.progbar.setToolTip("")
        self.progbar.setStatusTip("")
        self.progbar.setWhatsThis("")
        self.progbar.setAccessibleName("")
        self.progbar.setProperty("value", 0)
        self.progbar.setTextVisible(False)
        self.progbar.setInvertedAppearance(False)
        self.progbar.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progbar.setObjectName("progbar")
        self.gridLayout_18.addWidget(self.progbar, 0, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_18.addItem(spacerItem, 0, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_18, 1, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lbl_score_info_3 = QtWidgets.QLabel(self.tab_CS_GA)
        self.lbl_score_info_3.setObjectName("lbl_score_info_3")
        self.gridLayout_3.addWidget(self.lbl_score_info_3, 4, 3, 1, 1)
        self.lbl_converge_inf = QtWidgets.QLabel(self.tab_CS_GA)
        self.lbl_converge_inf.setObjectName("lbl_converge_inf")
        self.gridLayout_3.addWidget(self.lbl_converge_inf, 3, 3, 1, 1)
        self.lbl_mut = QtWidgets.QLabel(self.tab_CS_GA)
        self.lbl_mut.setStyleSheet("font: 12pt \"Ubuntu\";\n"
"color: rgb(0, 0, 0);")
        self.lbl_mut.setObjectName("lbl_mut")
        self.gridLayout_3.addWidget(self.lbl_mut, 2, 0, 1, 1)
        self.lbl_nconf_info_3 = QtWidgets.QLabel(self.tab_CS_GA)
        self.lbl_nconf_info_3.setObjectName("lbl_nconf_info_3")
        self.gridLayout_3.addWidget(self.lbl_nconf_info_3, 0, 3, 1, 1)
        self.txt_child = QtWidgets.QLineEdit(self.tab_CS_GA)
        self.txt_child.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_child.setObjectName("txt_child")
        self.gridLayout_3.addWidget(self.txt_child, 1, 1, 1, 1)
        self.lbl_score_1 = QtWidgets.QLabel(self.tab_CS_GA)
        self.lbl_score_1.setStyleSheet("font: 12pt \"Ubuntu\";\n"
"color: rgb(0, 0, 0);")
        self.lbl_score_1.setObjectName("lbl_score_1")
        self.gridLayout_3.addWidget(self.lbl_score_1, 4, 0, 1, 1)
        self.lbl_mutability_info_3 = QtWidgets.QLabel(self.tab_CS_GA)
        self.lbl_mutability_info_3.setObjectName("lbl_mutability_info_3")
        self.gridLayout_3.addWidget(self.lbl_mutability_info_3, 2, 3, 1, 1)
        self.txt_mut = QtWidgets.QLineEdit(self.tab_CS_GA)
        self.txt_mut.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_mut.setObjectName("txt_mut")
        self.gridLayout_3.addWidget(self.txt_mut, 2, 1, 1, 1)
        self.txt_ncon = QtWidgets.QLineEdit(self.tab_CS_GA)
        self.txt_ncon.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_ncon.setObjectName("txt_ncon")
        self.gridLayout_3.addWidget(self.txt_ncon, 0, 1, 1, 1)
        self.lbl_children_info_3 = QtWidgets.QLabel(self.tab_CS_GA)
        self.lbl_children_info_3.setObjectName("lbl_children_info_3")
        self.gridLayout_3.addWidget(self.lbl_children_info_3, 1, 3, 1, 1)
        self.lbl_conv = QtWidgets.QLabel(self.tab_CS_GA)
        self.lbl_conv.setStyleSheet("font: 12pt \"Ubuntu\";\n"
"color: rgb(0, 0, 0);")
        self.lbl_conv.setObjectName("lbl_conv")
        self.gridLayout_3.addWidget(self.lbl_conv, 3, 0, 1, 1)
        self.lbl_child = QtWidgets.QLabel(self.tab_CS_GA)
        self.lbl_child.setStyleSheet("font: 12pt \"Ubuntu\";\n"
"color: rgb(0, 0, 0);")
        self.lbl_child.setObjectName("lbl_child")
        self.gridLayout_3.addWidget(self.lbl_child, 1, 0, 1, 1)
        self.txt_conv = QtWidgets.QLineEdit(self.tab_CS_GA)
        self.txt_conv.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_conv.setObjectName("txt_conv")
        self.gridLayout_3.addWidget(self.txt_conv, 3, 1, 1, 1)
        self.lbl_ncon = QtWidgets.QLabel(self.tab_CS_GA)
        self.lbl_ncon.setStyleSheet("font: 12pt \"Ubuntu\";\n"
"color: rgb(0, 0, 0);")
        self.lbl_ncon.setObjectName("lbl_ncon")
        self.gridLayout_3.addWidget(self.lbl_ncon, 0, 0, 1, 1)
        self.txt_scor = QtWidgets.QLineEdit(self.tab_CS_GA)
        self.txt_scor.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_scor.setObjectName("txt_scor")
        self.gridLayout_3.addWidget(self.txt_scor, 4, 1, 1, 1)
        self.lbl_ffe_info = QtWidgets.QLabel(self.tab_CS_GA)
        self.lbl_ffe_info.setStyleSheet("font: 12pt \"Ubuntu\";\n"
"color: rgb(0, 0, 0);")
        self.lbl_ffe_info.setObjectName("lbl_ffe_info")
        self.gridLayout_3.addWidget(self.lbl_ffe_info, 5, 0, 1, 1)
        self.cbox_energyfield = QtWidgets.QComboBox(self.tab_CS_GA)
        self.cbox_energyfield.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cbox_energyfield.setStyleSheet("selection-background-color: rgb(0, 85, 255);")
        self.cbox_energyfield.setObjectName("cbox_energyfield")
        self.cbox_energyfield.addItem("")
        self.cbox_energyfield.addItem("")
        self.cbox_energyfield.addItem("")
        self.cbox_energyfield.addItem("")
        self.cbox_energyfield.addItem("")
        self.gridLayout_3.addWidget(self.cbox_energyfield, 5, 1, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.tab_CS_GA)
        self.label_24.setStyleSheet("font: 12pt \"Ubuntu\";\n"
"color: rgb(0, 0, 0);")
        self.label_24.setObjectName("label_24")
        self.gridLayout_3.addWidget(self.label_24, 0, 6, 1, 1)
        self.btn_lowerenergies = QtWidgets.QPushButton(self.tab_CS_GA)
        self.btn_lowerenergies.setObjectName("btn_lowerenergies")
        self.gridLayout_3.addWidget(self.btn_lowerenergies, 0, 8, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 0, 5, 1, 1)
        self.ln_confs = QtWidgets.QLineEdit(self.tab_CS_GA)
        self.ln_confs.setObjectName("ln_confs")
        self.gridLayout_3.addWidget(self.ln_confs, 0, 7, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 0, 11, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem3, 0, 12, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem4, 0, 9, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem5, 0, 10, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem6, 0, 4, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.tab_CS_GA)
        self.label_33.setStyleSheet("font: 12pt \"Ubuntu\";\n"
"color: rgb(0, 0, 0);")
        self.label_33.setObjectName("label_33")
        self.gridLayout_3.addWidget(self.label_33, 1, 6, 1, 1)
        self.ln_exportConformers = QtWidgets.QLineEdit(self.tab_CS_GA)
        self.ln_exportConformers.setObjectName("ln_exportConformers")
        self.gridLayout_3.addWidget(self.ln_exportConformers, 1, 7, 1, 1)
        self.btn_exportConformers = QtWidgets.QPushButton(self.tab_CS_GA)
        self.btn_exportConformers.setObjectName("btn_exportConformers")
        self.gridLayout_3.addWidget(self.btn_exportConformers, 1, 8, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.tab_CS_GA)
        self.label_34.setStyleSheet("font: 12pt \"Ubuntu\";\n"
"color: rgb(0, 0, 0);")
        self.label_34.setObjectName("label_34")
        self.gridLayout_3.addWidget(self.label_34, 2, 6, 1, 1)
        self.ln_overlapConfs = QtWidgets.QLineEdit(self.tab_CS_GA)
        self.ln_overlapConfs.setObjectName("ln_overlapConfs")
        self.gridLayout_3.addWidget(self.ln_overlapConfs, 2, 7, 1, 1)
        self.btn_overlapConfs = QtWidgets.QPushButton(self.tab_CS_GA)
        self.btn_overlapConfs.setObjectName("btn_overlapConfs")
        self.gridLayout_3.addWidget(self.btn_overlapConfs, 2, 8, 1, 1)
        self.chkbox_overlapALL = QtWidgets.QCheckBox(self.tab_CS_GA)
        self.chkbox_overlapALL.setObjectName("chkbox_overlapALL")
        self.gridLayout_3.addWidget(self.chkbox_overlapALL, 2, 9, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 2, 0, 1, 1)
        self.gridLayout_36 = QtWidgets.QGridLayout()
        self.gridLayout_36.setObjectName("gridLayout_36")
        self.label_7 = QtWidgets.QLabel(self.tab_CS_GA)
        self.label_7.setStyleSheet("font: 12pt \"Ubuntu\";\n"
"color: rgb(0, 0, 0);")
        self.label_7.setObjectName("label_7")
        self.gridLayout_36.addWidget(self.label_7, 0, 18, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_36.addItem(spacerItem7, 1, 5, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_36.addItem(spacerItem8, 1, 0, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_36.addItem(spacerItem9, 1, 12, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_36.addItem(spacerItem10, 1, 14, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_36.addItem(spacerItem11, 1, 16, 1, 1)
        self.btn_energy_GA_run = QtWidgets.QPushButton(self.tab_CS_GA)
        self.btn_energy_GA_run.setObjectName("btn_energy_GA_run")
        self.gridLayout_36.addWidget(self.btn_energy_GA_run, 1, 18, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_36.addItem(spacerItem12, 1, 8, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_36.addItem(spacerItem13, 1, 13, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_36.addItem(spacerItem14, 1, 19, 1, 1)
        self.btn_GA_run = QtWidgets.QPushButton(self.tab_CS_GA)
        self.btn_GA_run.setObjectName("btn_GA_run")
        self.gridLayout_36.addWidget(self.btn_GA_run, 1, 11, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_36.addItem(spacerItem15, 1, 15, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_36.addItem(spacerItem16, 1, 21, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.tab_CS_GA)
        self.label_4.setStyleSheet("font: 12pt \"Ubuntu\";\n"
"color: rgb(0, 0, 0);")
        self.label_4.setObjectName("label_4")
        self.gridLayout_36.addWidget(self.label_4, 1, 3, 1, 1)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_36.addItem(spacerItem17, 1, 9, 1, 1)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_36.addItem(spacerItem18, 1, 20, 1, 1)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_36.addItem(spacerItem19, 1, 17, 1, 1)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_36.addItem(spacerItem20, 1, 1, 1, 1)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_36.addItem(spacerItem21, 1, 4, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tab_CS_GA)
        self.label_2.setStyleSheet("font: 12pt \"Ubuntu\";\n"
"color: rgb(0, 0, 0);")
        self.label_2.setObjectName("label_2")
        self.gridLayout_36.addWidget(self.label_2, 0, 11, 1, 1)
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_36.addItem(spacerItem22, 1, 7, 1, 1)
        spacerItem23 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_36.addItem(spacerItem23, 1, 2, 1, 1)
        spacerItem24 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_36.addItem(spacerItem24, 1, 10, 1, 1)
        spacerItem25 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_36.addItem(spacerItem25, 0, 6, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_36, 3, 0, 1, 1)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.txt_log_show = QtWidgets.QTextEdit(self.tab_CS_GA)
        self.txt_log_show.setObjectName("txt_log_show")
        self.horizontalLayout_11.addWidget(self.txt_log_show)
        self.txt_conformer_show = QtWidgets.QTextEdit(self.tab_CS_GA)
        self.txt_conformer_show.setObjectName("txt_conformer_show")
        self.horizontalLayout_11.addWidget(self.txt_conformer_show)
        self.txt_energy_show = QtWidgets.QTextEdit(self.tab_CS_GA)
        self.txt_energy_show.setObjectName("txt_energy_show")
        self.horizontalLayout_11.addWidget(self.txt_energy_show)
        self.gridLayout_4.addLayout(self.horizontalLayout_11, 4, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab_CS_GA, "")
        self.gridLayout_2.addWidget(self.tabWidget_2, 0, 0, 1, 1)
        self.tab_CS.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.btn_automaticBoltz = QtWidgets.QPushButton(self.tab_2)
        self.btn_automaticBoltz.setObjectName("btn_automaticBoltz")
        self.gridLayout_6.addWidget(self.btn_automaticBoltz, 1, 4, 1, 1)
        self.txt_tempboltz = QtWidgets.QLineEdit(self.tab_2)
        self.txt_tempboltz.setObjectName("txt_tempboltz")
        self.gridLayout_6.addWidget(self.txt_tempboltz, 4, 3, 1, 1)
        self.lbl_tempboltz = QtWidgets.QLabel(self.tab_2)
        self.lbl_tempboltz.setStyleSheet("font: 12pt \"Ubuntu\";\n"
"color: rgb(0, 0, 0);")
        self.lbl_tempboltz.setObjectName("lbl_tempboltz")
        self.gridLayout_6.addWidget(self.lbl_tempboltz, 4, 1, 1, 1)
        self.txt_nconfboltz = QtWidgets.QLineEdit(self.tab_2)
        self.txt_nconfboltz.setObjectName("txt_nconfboltz")
        self.gridLayout_6.addWidget(self.txt_nconfboltz, 5, 3, 1, 1)
        self.cbox_unityboltz = QtWidgets.QComboBox(self.tab_2)
        self.cbox_unityboltz.setStyleSheet("selection-background-color: rgb(0, 85, 255);")
        self.cbox_unityboltz.setObjectName("cbox_unityboltz")
        self.cbox_unityboltz.addItem("")
        self.cbox_unityboltz.addItem("")
        self.gridLayout_6.addWidget(self.cbox_unityboltz, 3, 3, 1, 1)
        spacerItem26 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem26, 4, 0, 1, 1)
        self.lbl_nconfboltz = QtWidgets.QLabel(self.tab_2)
        self.lbl_nconfboltz.setStyleSheet("font: 12pt \"Ubuntu\";\n"
"color: rgb(0, 0, 0);")
        self.lbl_nconfboltz.setObjectName("lbl_nconfboltz")
        self.gridLayout_6.addWidget(self.lbl_nconfboltz, 5, 1, 1, 1)
        self.ln_automaticboltz = QtWidgets.QLineEdit(self.tab_2)
        self.ln_automaticboltz.setObjectName("ln_automaticboltz")
        self.gridLayout_6.addWidget(self.ln_automaticboltz, 1, 3, 1, 1)
        spacerItem27 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem27, 9, 1, 1, 1)
        spacerItem28 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem28, 0, 1, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.tab_2)
        self.label_26.setStyleSheet("font: 12pt \"Ubuntu\";\n"
"color: rgb(0, 0, 0);")
        self.label_26.setObjectName("label_26")
        self.gridLayout_6.addWidget(self.label_26, 3, 1, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.tab_2)
        self.label_27.setStyleSheet("font: 12pt \"Ubuntu\";\n"
"color: rgb(0, 0, 0);")
        self.label_27.setObjectName("label_27")
        self.gridLayout_6.addWidget(self.label_27, 1, 1, 1, 1)
        self.btn_gerar_tables = QtWidgets.QPushButton(self.tab_2)
        self.btn_gerar_tables.setObjectName("btn_gerar_tables")
        self.gridLayout_6.addWidget(self.btn_gerar_tables, 5, 4, 1, 1)
        spacerItem29 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem29, 1, 6, 1, 1)
        self.btn_run_boltz = QtWidgets.QPushButton(self.tab_2)
        self.btn_run_boltz.setObjectName("btn_run_boltz")
        self.gridLayout_6.addWidget(self.btn_run_boltz, 5, 5, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        self.grid_tables = QtWidgets.QGridLayout()
        self.grid_tables.setObjectName("grid_tables")
        self.tables = QtWidgets.QTableWidget(self.tab_2)
        self.tables.setObjectName("tables")
        self.tables.setColumnCount(0)
        self.tables.setRowCount(0)
        self.grid_tables.addWidget(self.tables, 0, 0, 1, 1)
        self.gridLayout_9.addLayout(self.grid_tables, 0, 1, 1, 1)
        self.tab_CS.addTab(self.tab_2, "")
        self.tab_ssnmr = QtWidgets.QWidget()
        self.tab_ssnmr.setObjectName("tab_ssnmr")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab_ssnmr)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lbl_show_dir_cs_2 = QtWidgets.QLabel(self.tab_ssnmr)
        self.lbl_show_dir_cs_2.setText("")
        self.lbl_show_dir_cs_2.setObjectName("lbl_show_dir_cs_2")
        self.verticalLayout_2.addWidget(self.lbl_show_dir_cs_2)
        self.gridLayout_7.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.progbar_qe = QtWidgets.QProgressBar(self.tab_ssnmr)
        self.progbar_qe.setStyleSheet("")
        self.progbar_qe.setProperty("value", 0)
        self.progbar_qe.setTextVisible(False)
        self.progbar_qe.setObjectName("progbar_qe")
        self.verticalLayout_3.addWidget(self.progbar_qe)
        self.gridLayout_7.addLayout(self.verticalLayout_3, 0, 1, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_13 = QtWidgets.QLabel(self.tab_ssnmr)
        self.label_13.setStyleSheet("font: 12pt \"Ubuntu\";\n"
"color: rgb(0, 0, 0);")
        self.label_13.setObjectName("label_13")
        self.gridLayout_5.addWidget(self.label_13, 5, 0, 1, 1)
        spacerItem30 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem30, 2, 20, 1, 1)
        spacerItem31 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem31, 2, 19, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.tab_ssnmr)
        self.label_14.setStyleSheet("font: 12pt \"Ubuntu\";\n"
"color: rgb(0, 0, 0);")
        self.label_14.setObjectName("label_14")
        self.gridLayout_5.addWidget(self.label_14, 0, 3, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.tab_ssnmr)
        self.label_28.setStyleSheet("font: 12pt \"Ubuntu\";\n"
"color: rgb(0, 0, 0);")
        self.label_28.setObjectName("label_28")
        self.gridLayout_5.addWidget(self.label_28, 4, 3, 1, 1)
        self.chkbox_threadsnmr = QtWidgets.QCheckBox(self.tab_ssnmr)
        self.chkbox_threadsnmr.setEnabled(True)
        self.chkbox_threadsnmr.setCheckable(True)
        self.chkbox_threadsnmr.setChecked(False)
        self.chkbox_threadsnmr.setAutoRepeat(False)
        self.chkbox_threadsnmr.setObjectName("chkbox_threadsnmr")
        self.gridLayout_5.addWidget(self.chkbox_threadsnmr, 0, 2, 1, 1)
        self.ln_acuraccyscf = QtWidgets.QLineEdit(self.tab_ssnmr)
        self.ln_acuraccyscf.setObjectName("ln_acuraccyscf")
        self.gridLayout_5.addWidget(self.ln_acuraccyscf, 5, 1, 1, 1)
        self.btn_pwout = QtWidgets.QPushButton(self.tab_ssnmr)
        self.btn_pwout.setObjectName("btn_pwout")
        self.gridLayout_5.addWidget(self.btn_pwout, 1, 5, 1, 1)
        self.ln_kgrid = QtWidgets.QLineEdit(self.tab_ssnmr)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ln_kgrid.sizePolicy().hasHeightForWidth())
        self.ln_kgrid.setSizePolicy(sizePolicy)
        self.ln_kgrid.setObjectName("ln_kgrid")
        self.gridLayout_5.addWidget(self.ln_kgrid, 3, 1, 1, 1)
        self.ln_stepscf = QtWidgets.QLineEdit(self.tab_ssnmr)
        self.ln_stepscf.setObjectName("ln_stepscf")
        self.gridLayout_5.addWidget(self.ln_stepscf, 4, 1, 1, 1)
        spacerItem32 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem32, 5, 12, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.tab_ssnmr)
        self.label_5.setStyleSheet("font: 12pt \"Ubuntu\";\n"
"color: rgb(0, 0, 0);")
        self.label_5.setObjectName("label_5")
        self.gridLayout_5.addWidget(self.label_5, 3, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.tab_ssnmr)
        self.label_6.setStyleSheet("font: 12pt \"Ubuntu\";\n"
"color: rgb(0, 0, 0);")
        self.label_6.setObjectName("label_6")
        self.gridLayout_5.addWidget(self.label_6, 1, 0, 1, 1)
        self.cbox_filterscfout = QtWidgets.QComboBox(self.tab_ssnmr)
        self.cbox_filterscfout.setStyleSheet("selection-background-color: rgb(0, 85, 255);")
        self.cbox_filterscfout.setObjectName("cbox_filterscfout")
        self.cbox_filterscfout.addItem("")
        self.cbox_filterscfout.addItem("")
        self.cbox_filterscfout.addItem("")
        self.gridLayout_5.addWidget(self.cbox_filterscfout, 3, 5, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.tab_ssnmr)
        self.label_32.setStyleSheet("font: 12pt \"Ubuntu\";\n"
"color: rgb(0, 0, 0);")
        self.label_32.setObjectName("label_32")
        self.gridLayout_5.addWidget(self.label_32, 0, 0, 1, 1)
        self.ln_ibrav = QtWidgets.QLineEdit(self.tab_ssnmr)
        self.ln_ibrav.setObjectName("ln_ibrav")
        self.gridLayout_5.addWidget(self.ln_ibrav, 1, 1, 1, 1)
        self.ln_cutoff = QtWidgets.QLineEdit(self.tab_ssnmr)
        self.ln_cutoff.setObjectName("ln_cutoff")
        self.gridLayout_5.addWidget(self.ln_cutoff, 2, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.tab_ssnmr)
        self.label_16.setStyleSheet("font: 12pt \"Ubuntu\";\n"
"color: rgb(0, 0, 0);")
        self.label_16.setObjectName("label_16")
        self.gridLayout_5.addWidget(self.label_16, 2, 3, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.tab_ssnmr)
        self.label_15.setStyleSheet("font: 12pt \"Ubuntu\";\n"
"color: rgb(0, 0, 0);")
        self.label_15.setObjectName("label_15")
        self.gridLayout_5.addWidget(self.label_15, 1, 3, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.tab_ssnmr)
        self.label_10.setStyleSheet("font: 12pt \"Ubuntu\";\n"
"color: rgb(0, 0, 0);")
        self.label_10.setObjectName("label_10")
        self.gridLayout_5.addWidget(self.label_10, 4, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.tab_ssnmr)
        self.label_11.setObjectName("label_11")
        self.gridLayout_5.addWidget(self.label_11, 1, 2, 1, 1)
        self.cbox_filtergipawout = QtWidgets.QComboBox(self.tab_ssnmr)
        self.cbox_filtergipawout.setStyleSheet("selection-background-color: rgb(0, 85, 255);")
        self.cbox_filtergipawout.setObjectName("cbox_filtergipawout")
        self.cbox_filtergipawout.addItem("")
        self.cbox_filtergipawout.addItem("")
        self.cbox_filtergipawout.addItem("")
        self.cbox_filtergipawout.addItem("")
        self.cbox_filtergipawout.addItem("")
        self.cbox_filtergipawout.addItem("")
        self.cbox_filtergipawout.addItem("")
        self.cbox_filtergipawout.addItem("")
        self.gridLayout_5.addWidget(self.cbox_filtergipawout, 4, 5, 1, 1)
        self.btn_pwin = QtWidgets.QPushButton(self.tab_ssnmr)
        self.btn_pwin.setObjectName("btn_pwin")
        self.gridLayout_5.addWidget(self.btn_pwin, 0, 5, 1, 1)
        self.ln_threadsnmr = QtWidgets.QLineEdit(self.tab_ssnmr)
        self.ln_threadsnmr.setObjectName("ln_threadsnmr")
        self.gridLayout_5.addWidget(self.ln_threadsnmr, 0, 1, 1, 1)
        spacerItem33 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem33, 5, 13, 1, 1)
        self.btn_gipaw = QtWidgets.QPushButton(self.tab_ssnmr)
        self.btn_gipaw.setObjectName("btn_gipaw")
        self.gridLayout_5.addWidget(self.btn_gipaw, 2, 5, 1, 1)
        spacerItem34 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem34, 5, 11, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.tab_ssnmr)
        self.label_3.setStyleSheet("font: 12pt \"Ubuntu\";\n"
"color: rgb(0, 0, 0);")
        self.label_3.setObjectName("label_3")
        self.gridLayout_5.addWidget(self.label_3, 2, 0, 1, 1)
        spacerItem35 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem35, 2, 21, 1, 1)
        spacerItem36 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem36, 5, 10, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.tab_ssnmr)
        self.label_25.setStyleSheet("font: 12pt \"Ubuntu\";\n"
"color: rgb(0, 0, 0);")
        self.label_25.setObjectName("label_25")
        self.gridLayout_5.addWidget(self.label_25, 3, 3, 1, 1)
        spacerItem37 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem37, 5, 8, 1, 1)
        spacerItem38 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem38, 5, 9, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.tab_ssnmr)
        self.label_22.setStyleSheet("font: 12pt \"Ubuntu\";\n"
"color: rgb(0, 0, 0);")
        self.label_22.setObjectName("label_22")
        self.gridLayout_5.addWidget(self.label_22, 5, 3, 1, 1)
        self.btn_scfopt = QtWidgets.QPushButton(self.tab_ssnmr)
        self.btn_scfopt.setObjectName("btn_scfopt")
        self.gridLayout_5.addWidget(self.btn_scfopt, 5, 5, 1, 1)
        self.ln_rangecutoff = QtWidgets.QLineEdit(self.tab_ssnmr)
        self.ln_rangecutoff.setObjectName("ln_rangecutoff")
        self.gridLayout_5.addWidget(self.ln_rangecutoff, 5, 6, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.tab_ssnmr)
        self.label_20.setObjectName("label_20")
        self.gridLayout_5.addWidget(self.label_20, 5, 7, 1, 1)
        self.chk_kauto = QtWidgets.QCheckBox(self.tab_ssnmr)
        self.chk_kauto.setObjectName("chk_kauto")
        self.gridLayout_5.addWidget(self.chk_kauto, 3, 2, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_5, 1, 0, 1, 2)
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_9 = QtWidgets.QLabel(self.tab_ssnmr)
        self.label_9.setStyleSheet("font: 12pt \"Ubuntu\";\n"
"color: rgb(0, 0, 0);")
        self.label_9.setObjectName("label_9")
        self.gridLayout_10.addWidget(self.label_9, 1, 0, 1, 1)
        self.cbox_pseudop = QtWidgets.QComboBox(self.tab_ssnmr)
        self.cbox_pseudop.setStyleSheet("selection-background-color: rgb(0, 85, 255);")
        self.cbox_pseudop.setObjectName("cbox_pseudop")
        self.cbox_pseudop.addItem("")
        self.cbox_pseudop.setItemText(0, "New-Gipaw")
        self.cbox_pseudop.addItem("")
        self.gridLayout_10.addWidget(self.cbox_pseudop, 2, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.tab_ssnmr)
        self.label_8.setStyleSheet("font: 12pt \"Ubuntu\";\n"
"color: rgb(0, 0, 0);")
        self.label_8.setObjectName("label_8")
        self.gridLayout_10.addWidget(self.label_8, 2, 0, 1, 1)
        self.cbox_diagonalization = QtWidgets.QComboBox(self.tab_ssnmr)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(245, 245, 245))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(245, 245, 245))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(245, 245, 245))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(245, 245, 245))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(245, 245, 245))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(245, 245, 245))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(245, 245, 245))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(245, 245, 245))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(245, 245, 245))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        self.cbox_diagonalization.setPalette(palette)
        self.cbox_diagonalization.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.cbox_diagonalization.setMouseTracking(False)
        self.cbox_diagonalization.setStyleSheet("selection-background-color: rgb(0, 85, 255);")
        self.cbox_diagonalization.setEditable(False)
        self.cbox_diagonalization.setDuplicatesEnabled(False)
        self.cbox_diagonalization.setObjectName("cbox_diagonalization")
        self.cbox_diagonalization.addItem("")
        self.cbox_diagonalization.addItem("")
        self.gridLayout_10.addWidget(self.cbox_diagonalization, 1, 1, 1, 1)
        spacerItem39 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem39, 1, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.tab_ssnmr)
        self.label_12.setStyleSheet("font: 12pt \"Ubuntu\";\n"
"color: rgb(0, 0, 0);")
        self.label_12.setObjectName("label_12")
        self.gridLayout_10.addWidget(self.label_12, 0, 0, 1, 1)
        self.cbox_nosym = QtWidgets.QComboBox(self.tab_ssnmr)
        self.cbox_nosym.setStyleSheet("selection-background-color: rgb(0, 85, 255);")
        self.cbox_nosym.setObjectName("cbox_nosym")
        self.cbox_nosym.addItem("")
        self.cbox_nosym.addItem("")
        self.gridLayout_10.addWidget(self.cbox_nosym, 0, 1, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_10, 2, 0, 1, 1)
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.txt_pwin = QtWidgets.QTextEdit(self.tab_ssnmr)
        self.txt_pwin.setObjectName("txt_pwin")
        self.gridLayout_8.addWidget(self.txt_pwin, 1, 0, 1, 1)
        self.txt_gipaw = QtWidgets.QTextEdit(self.tab_ssnmr)
        self.txt_gipaw.setObjectName("txt_gipaw")
        self.gridLayout_8.addWidget(self.txt_gipaw, 1, 2, 1, 1)
        self.txt_pwout = QtWidgets.QTextEdit(self.tab_ssnmr)
        self.txt_pwout.setObjectName("txt_pwout")
        self.gridLayout_8.addWidget(self.txt_pwout, 1, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.tab_ssnmr)
        self.label_19.setObjectName("label_19")
        self.gridLayout_8.addWidget(self.label_19, 0, 2, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.tab_ssnmr)
        self.label_18.setObjectName("label_18")
        self.gridLayout_8.addWidget(self.label_18, 0, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.tab_ssnmr)
        self.label_17.setObjectName("label_17")
        self.gridLayout_8.addWidget(self.label_17, 0, 0, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_8, 3, 0, 1, 2)
        self.tab_CS.addTab(self.tab_ssnmr, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setObjectName("gridLayout_11")
        spacerItem40 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem40, 0, 11, 1, 1)
        self.btn_nmrgraphGIPAW = QtWidgets.QPushButton(self.tab_3)
        self.btn_nmrgraphGIPAW.setObjectName("btn_nmrgraphGIPAW")
        self.gridLayout_11.addWidget(self.btn_nmrgraphGIPAW, 0, 1, 1, 1)
        self.line = QtWidgets.QFrame(self.tab_3)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_11.addWidget(self.line, 0, 4, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.tab_3)
        self.label_36.setStyleSheet("font: 12pt \"Ubuntu\";\n"
"color: rgb(0, 0, 0);")
        self.label_36.setObjectName("label_36")
        self.gridLayout_11.addWidget(self.label_36, 0, 0, 1, 1)
        spacerItem41 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem41, 0, 12, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.tab_3)
        self.label_21.setStyleSheet("font: 12pt \"Ubuntu\";\n"
"color: rgb(0, 0, 0);")
        self.label_21.setObjectName("label_21")
        self.gridLayout_11.addWidget(self.label_21, 1, 0, 1, 1)
        self.ln_tensors = QtWidgets.QLineEdit(self.tab_3)
        self.ln_tensors.setObjectName("ln_tensors")
        self.gridLayout_11.addWidget(self.ln_tensors, 0, 8, 1, 1)
        self.cbox_nmrgraphGIPAW = QtWidgets.QComboBox(self.tab_3)
        self.cbox_nmrgraphGIPAW.setStyleSheet("selection-background-color: rgb(0, 85, 255);")
        self.cbox_nmrgraphGIPAW.setObjectName("cbox_nmrgraphGIPAW")
        self.cbox_nmrgraphGIPAW.addItem("")
        self.cbox_nmrgraphGIPAW.addItem("")
        self.cbox_nmrgraphGIPAW.addItem("")
        self.cbox_nmrgraphGIPAW.addItem("")
        self.cbox_nmrgraphGIPAW.addItem("")
        self.cbox_nmrgraphGIPAW.addItem("")
        self.cbox_nmrgraphGIPAW.addItem("")
        self.gridLayout_11.addWidget(self.cbox_nmrgraphGIPAW, 0, 3, 1, 1)
        self.btn_pwscfPLOT = QtWidgets.QPushButton(self.tab_3)
        self.btn_pwscfPLOT.setObjectName("btn_pwscfPLOT")
        self.gridLayout_11.addWidget(self.btn_pwscfPLOT, 1, 1, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.tab_3)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_11.addWidget(self.line_2, 0, 6, 1, 1)
        self.btn_plotMANUAL = QtWidgets.QPushButton(self.tab_3)
        self.btn_plotMANUAL.setObjectName("btn_plotMANUAL")
        self.gridLayout_11.addWidget(self.btn_plotMANUAL, 0, 10, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.tab_3)
        self.label_37.setStyleSheet("font: 12pt \"Ubuntu\";\n"
"color: rgb(0, 0, 0);")
        self.label_37.setObjectName("label_37")
        self.gridLayout_11.addWidget(self.label_37, 0, 7, 1, 1)
        self.ln_reference = QtWidgets.QLineEdit(self.tab_3)
        self.ln_reference.setObjectName("ln_reference")
        self.gridLayout_11.addWidget(self.ln_reference, 0, 5, 1, 1)
        self.btn_nmrgraphGIAO = QtWidgets.QPushButton(self.tab_3)
        self.btn_nmrgraphGIAO.setObjectName("btn_nmrgraphGIAO")
        self.gridLayout_11.addWidget(self.btn_nmrgraphGIAO, 0, 2, 1, 1)
        self.gridLayout_15.addLayout(self.gridLayout_11, 0, 0, 1, 1)
        self.MplWidget = MplWidget(self.tab_3)
        self.MplWidget.setObjectName("MplWidget")
        self.gridLayout_15.addWidget(self.MplWidget, 1, 0, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.tabWidget = QtWidgets.QTabWidget(self.tab_3)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.gridLayout_12 = QtWidgets.QGridLayout()
        self.gridLayout_12.setObjectName("gridLayout_12")
        spacerItem42 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem42, 1, 8, 1, 1)
        spacerItem43 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem43, 1, 7, 1, 1)
        self.btn_resetPLOT = QtWidgets.QPushButton(self.tab_4)
        self.btn_resetPLOT.setObjectName("btn_resetPLOT")
        self.gridLayout_12.addWidget(self.btn_resetPLOT, 0, 3, 1, 1)
        spacerItem44 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem44, 1, 9, 1, 1)
        self.ln_suavization = QtWidgets.QLineEdit(self.tab_4)
        self.ln_suavization.setObjectName("ln_suavization")
        self.gridLayout_12.addWidget(self.ln_suavization, 4, 1, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.tab_4)
        self.label_39.setObjectName("label_39")
        self.gridLayout_12.addWidget(self.label_39, 1, 3, 1, 1)
        spacerItem45 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem45, 1, 21, 1, 1)
        self.ln_width = QtWidgets.QLineEdit(self.tab_4)
        self.ln_width.setObjectName("ln_width")
        self.gridLayout_12.addWidget(self.ln_width, 3, 1, 1, 1)
        self.ln_ymax = QtWidgets.QLineEdit(self.tab_4)
        self.ln_ymax.setObjectName("ln_ymax")
        self.gridLayout_12.addWidget(self.ln_ymax, 1, 5, 1, 1)
        spacerItem46 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem46, 1, 19, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.tab_4)
        self.label_38.setObjectName("label_38")
        self.gridLayout_12.addWidget(self.label_38, 1, 0, 1, 1)
        self.ln_ymin = QtWidgets.QLineEdit(self.tab_4)
        self.ln_ymin.setObjectName("ln_ymin")
        self.gridLayout_12.addWidget(self.ln_ymin, 1, 4, 1, 1)
        spacerItem47 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem47, 1, 12, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.tab_4)
        self.label_41.setObjectName("label_41")
        self.gridLayout_12.addWidget(self.label_41, 3, 0, 1, 1)
        spacerItem48 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem48, 1, 13, 1, 1)
        spacerItem49 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem49, 1, 11, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.tab_4)
        self.label_43.setObjectName("label_43")
        self.gridLayout_12.addWidget(self.label_43, 0, 0, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.tab_4)
        self.label_40.setObjectName("label_40")
        self.gridLayout_12.addWidget(self.label_40, 2, 0, 1, 1)
        self.ln_intensity = QtWidgets.QLineEdit(self.tab_4)
        self.ln_intensity.setObjectName("ln_intensity")
        self.gridLayout_12.addWidget(self.ln_intensity, 2, 1, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.tab_4)
        self.label_42.setObjectName("label_42")
        self.gridLayout_12.addWidget(self.label_42, 4, 0, 1, 1)
        spacerItem50 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem50, 1, 20, 1, 1)
        spacerItem51 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem51, 1, 22, 1, 1)
        self.cbox_lorentzianSticks = QtWidgets.QComboBox(self.tab_4)
        self.cbox_lorentzianSticks.setStyleSheet("selection-background-color: rgb(0, 85, 255);")
        self.cbox_lorentzianSticks.setObjectName("cbox_lorentzianSticks")
        self.cbox_lorentzianSticks.addItem("")
        self.cbox_lorentzianSticks.addItem("")
        self.gridLayout_12.addWidget(self.cbox_lorentzianSticks, 0, 1, 1, 1)
        self.ln_xmin = QtWidgets.QLineEdit(self.tab_4)
        self.ln_xmin.setObjectName("ln_xmin")
        self.gridLayout_12.addWidget(self.ln_xmin, 1, 1, 1, 1)
        self.ln_xmax = QtWidgets.QLineEdit(self.tab_4)
        self.ln_xmax.setObjectName("ln_xmax")
        self.gridLayout_12.addWidget(self.ln_xmax, 1, 2, 1, 1)
        spacerItem52 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem52, 1, 10, 1, 1)
        spacerItem53 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem53, 1, 6, 1, 1)
        self.gridLayout_14.addLayout(self.gridLayout_12, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_4, "")
        self.verticalLayout_5.addWidget(self.tabWidget)
        self.gridLayout_15.addLayout(self.verticalLayout_5, 2, 0, 1, 1)
        self.tab_CS.addTab(self.tab_3, "")
        self.gridLayout.addWidget(self.tab_CS, 0, 0, 1, 1)
        spyn_mainwindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(spyn_mainwindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1152, 23))
        self.menubar.setObjectName("menubar")
        self.menuFIle = QtWidgets.QMenu(self.menubar)
        self.menuFIle.setObjectName("menuFIle")
        self.menuExport = QtWidgets.QMenu(self.menuFIle)
        self.menuExport.setObjectName("menuExport")
        self.menuConformers = QtWidgets.QMenu(self.menuExport)
        self.menuConformers.setObjectName("menuConformers")
        self.menuGipaw = QtWidgets.QMenu(self.menuExport)
        self.menuGipaw.setObjectName("menuGipaw")
        self.menuPWscf = QtWidgets.QMenu(self.menuExport)
        self.menuPWscf.setObjectName("menuPWscf")
        self.menuImport = QtWidgets.QMenu(self.menuFIle)
        self.menuImport.setObjectName("menuImport")
        self.menuNMR_exp = QtWidgets.QMenu(self.menuImport)
        self.menuNMR_exp.setObjectName("menuNMR_exp")
        self.menuCalc = QtWidgets.QMenu(self.menubar)
        self.menuCalc.setObjectName("menuCalc")
        self.menuInput_Gaussian = QtWidgets.QMenu(self.menuCalc)
        self.menuInput_Gaussian.setObjectName("menuInput_Gaussian")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        spyn_mainwindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(spyn_mainwindow)
        self.statusbar.setObjectName("statusbar")
        spyn_mainwindow.setStatusBar(self.statusbar)
        self.menu_open = QtWidgets.QAction(spyn_mainwindow)
        self.menu_open.setObjectName("menu_open")
        self.menu_export_mol = QtWidgets.QAction(spyn_mainwindow)
        self.menu_export_mol.setObjectName("menu_export_mol")
        self.menu_export_mol2 = QtWidgets.QAction(spyn_mainwindow)
        self.menu_export_mol2.setObjectName("menu_export_mol2")
        self.menu_export_com = QtWidgets.QAction(spyn_mainwindow)
        self.menu_export_com.setObjectName("menu_export_com")
        self.menu_save = QtWidgets.QAction(spyn_mainwindow)
        self.menu_save.setObjectName("menu_save")
        self.menu_save_energy = QtWidgets.QAction(spyn_mainwindow)
        self.menu_save_energy.setObjectName("menu_save_energy")
        self.menu_save_conformers = QtWidgets.QAction(spyn_mainwindow)
        self.menu_save_conformers.setObjectName("menu_save_conformers")
        self.menu_save_PWscf_input = QtWidgets.QAction(spyn_mainwindow)
        self.menu_save_PWscf_input.setObjectName("menu_save_PWscf_input")
        self.menu_save_PWscf_output = QtWidgets.QAction(spyn_mainwindow)
        self.menu_save_PWscf_output.setObjectName("menu_save_PWscf_output")
        self.menu_save_gipaw_input = QtWidgets.QAction(spyn_mainwindow)
        self.menu_save_gipaw_input.setObjectName("menu_save_gipaw_input")
        self.menu_save_gipaw_output = QtWidgets.QAction(spyn_mainwindow)
        self.menu_save_gipaw_output.setObjectName("menu_save_gipaw_output")
        self.menu_quit = QtWidgets.QAction(spyn_mainwindow)
        self.menu_quit.setObjectName("menu_quit")
        self.menu_runCSGA = QtWidgets.QAction(spyn_mainwindow)
        self.menu_runCSGA.setObjectName("menu_runCSGA")
        self.run_cs_ff = QtWidgets.QAction(spyn_mainwindow)
        self.run_cs_ff.setObjectName("run_cs_ff")
        self.menu_runPWscf_input = QtWidgets.QAction(spyn_mainwindow)
        self.menu_runPWscf_input.setObjectName("menu_runPWscf_input")
        self.menu_runPWscf_output = QtWidgets.QAction(spyn_mainwindow)
        self.menu_runPWscf_output.setObjectName("menu_runPWscf_output")
        self.menu_runGipaw = QtWidgets.QAction(spyn_mainwindow)
        self.menu_runGipaw.setObjectName("menu_runGipaw")
        self.menu_tutorials = QtWidgets.QAction(spyn_mainwindow)
        self.menu_tutorials.setObjectName("menu_tutorials")
        self.menu_about = QtWidgets.QAction(spyn_mainwindow)
        self.menu_about.setObjectName("menu_about")
        self.menu_giao = QtWidgets.QAction(spyn_mainwindow)
        self.menu_giao.setObjectName("menu_giao")
        self.menu_optgiao = QtWidgets.QAction(spyn_mainwindow)
        self.menu_optgiao.setObjectName("menu_optgiao")
        self.menu_ConformersOut = QtWidgets.QAction(spyn_mainwindow)
        self.menu_ConformersOut.setObjectName("menu_ConformersOut")
        self.menu_PWscfOut = QtWidgets.QAction(spyn_mainwindow)
        self.menu_PWscfOut.setObjectName("menu_PWscfOut")
        self.menu_GipawOut = QtWidgets.QAction(spyn_mainwindow)
        self.menu_GipawOut.setObjectName("menu_GipawOut")
        self.menuExportConfs_sdf = QtWidgets.QAction(spyn_mainwindow)
        self.menuExportConfs_sdf.setObjectName("menuExportConfs_sdf")
        self.menuExportConfs_mol = QtWidgets.QAction(spyn_mainwindow)
        self.menuExportConfs_mol.setObjectName("menuExportConfs_mol")
        self.menuExportEnergy = QtWidgets.QAction(spyn_mainwindow)
        self.menuExportEnergy.setObjectName("menuExportEnergy")
        self.menuExportGipaw_In = QtWidgets.QAction(spyn_mainwindow)
        self.menuExportGipaw_In.setObjectName("menuExportGipaw_In")
        self.menuExportGipaw_Out = QtWidgets.QAction(spyn_mainwindow)
        self.menuExportGipaw_Out.setObjectName("menuExportGipaw_Out")
        self.menuExportPWscf_In = QtWidgets.QAction(spyn_mainwindow)
        self.menuExportPWscf_In.setObjectName("menuExportPWscf_In")
        self.menuExportPWscf_out = QtWidgets.QAction(spyn_mainwindow)
        self.menuExportPWscf_out.setObjectName("menuExportPWscf_out")
        self.menu_nmrexpCSV = QtWidgets.QAction(spyn_mainwindow)
        self.menu_nmrexpCSV.setObjectName("menu_nmrexpCSV")
        self.menu_nmrexpBruker = QtWidgets.QAction(spyn_mainwindow)
        self.menu_nmrexpBruker.setObjectName("menu_nmrexpBruker")
        self.menu_Giaoout = QtWidgets.QAction(spyn_mainwindow)
        self.menu_Giaoout.setObjectName("menu_Giaoout")
        self.menuConformers.addAction(self.menuExportConfs_sdf)
        self.menuConformers.addAction(self.menuExportConfs_mol)
        self.menuGipaw.addAction(self.menuExportGipaw_In)
        self.menuGipaw.addAction(self.menuExportGipaw_Out)
        self.menuPWscf.addAction(self.menuExportPWscf_In)
        self.menuPWscf.addAction(self.menuExportPWscf_out)
        self.menuExport.addAction(self.menuConformers.menuAction())
        self.menuExport.addAction(self.menuExportEnergy)
        self.menuExport.addAction(self.menuGipaw.menuAction())
        self.menuExport.addAction(self.menuPWscf.menuAction())
        self.menuNMR_exp.addAction(self.menu_nmrexpCSV)
        self.menuNMR_exp.addAction(self.menu_nmrexpBruker)
        self.menuImport.addAction(self.menu_ConformersOut)
        self.menuImport.addAction(self.menu_PWscfOut)
        self.menuImport.addAction(self.menu_GipawOut)
        self.menuImport.addAction(self.menu_Giaoout)
        self.menuImport.addAction(self.menuNMR_exp.menuAction())
        self.menuFIle.addAction(self.menu_open)
        self.menuFIle.addAction(self.menuImport.menuAction())
        self.menuFIle.addAction(self.menuExport.menuAction())
        self.menuFIle.addSeparator()
        self.menuFIle.addAction(self.menu_quit)
        self.menuInput_Gaussian.addAction(self.menu_giao)
        self.menuInput_Gaussian.addAction(self.menu_optgiao)
        self.menuCalc.addAction(self.menu_runCSGA)
        self.menuCalc.addAction(self.menu_runPWscf_input)
        self.menuCalc.addAction(self.menu_runPWscf_output)
        self.menuCalc.addAction(self.menu_runGipaw)
        self.menuCalc.addSeparator()
        self.menuCalc.addAction(self.menuInput_Gaussian.menuAction())
        self.menuHelp.addAction(self.menu_tutorials)
        self.menuAbout.addAction(self.menu_about)
        self.menubar.addAction(self.menuFIle.menuAction())
        self.menubar.addAction(self.menuCalc.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(spyn_mainwindow)
        self.tab_CS.setCurrentIndex(3)
        self.tabWidget_2.setCurrentIndex(0)
        self.cbox_diagonalization.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(spyn_mainwindow)

    def retranslateUi(self, spyn_mainwindow):
        _translate = QtCore.QCoreApplication.translate
        spyn_mainwindow.setWindowTitle(_translate("spyn_mainwindow", "Spyn"))
        self.label.setText(_translate("spyn_mainwindow", "Parameters"))
        self.lbl_score_info_3.setText(_translate("spyn_mainwindow", "Scoring function [rmsd|energy|minrmsd|minenergy]"))
        self.lbl_converge_inf.setText(_translate("spyn_mainwindow", "Number of identical generations before convergence"))
        self.lbl_mut.setText(_translate("spyn_mainwindow", "                     Mutability:"))
        self.lbl_nconf_info_3.setText(_translate("spyn_mainwindow", "Number of conformers to generate"))
        self.txt_child.setText(_translate("spyn_mainwindow", "5"))
        self.lbl_score_1.setText(_translate("spyn_mainwindow", "                            Score:"))
        self.lbl_mutability_info_3.setText(_translate("spyn_mainwindow", "Mutation frequency"))
        self.txt_mut.setText(_translate("spyn_mainwindow", "5"))
        self.txt_ncon.setText(_translate("spyn_mainwindow", "30"))
        self.lbl_children_info_3.setText(_translate("spyn_mainwindow", "Number of children to generate for each parent"))
        self.lbl_conv.setText(_translate("spyn_mainwindow", "                      Converge:"))
        self.lbl_child.setText(_translate("spyn_mainwindow", "                       Children :"))
        self.txt_conv.setText(_translate("spyn_mainwindow", "7"))
        self.lbl_ncon.setText(_translate("spyn_mainwindow", "                            Nconf:"))
        self.txt_scor.setText(_translate("spyn_mainwindow", "rmsd"))
        self.lbl_ffe_info.setText(_translate("spyn_mainwindow", "Force Field for Energy:"))
        self.cbox_energyfield.setItemText(0, _translate("spyn_mainwindow", "MMFF94"))
        self.cbox_energyfield.setItemText(1, _translate("spyn_mainwindow", "MMFF94s"))
        self.cbox_energyfield.setItemText(2, _translate("spyn_mainwindow", "UFF"))
        self.cbox_energyfield.setItemText(3, _translate("spyn_mainwindow", "Ghemical"))
        self.cbox_energyfield.setItemText(4, _translate("spyn_mainwindow", "GAFF"))
        self.label_24.setText(_translate("spyn_mainwindow", "    Lower energies:"))
        self.btn_lowerenergies.setText(_translate("spyn_mainwindow", "OK"))
        self.ln_confs.setText(_translate("spyn_mainwindow", "10"))
        self.label_33.setText(_translate("spyn_mainwindow", "Export conformer:"))
        self.ln_exportConformers.setText(_translate("spyn_mainwindow", "1;2;3"))
        self.btn_exportConformers.setText(_translate("spyn_mainwindow", "OK"))
        self.label_34.setText(_translate("spyn_mainwindow", "          Overlap plot:"))
        self.ln_overlapConfs.setText(_translate("spyn_mainwindow", "1;2;3"))
        self.btn_overlapConfs.setText(_translate("spyn_mainwindow", "OK"))
        self.chkbox_overlapALL.setText(_translate("spyn_mainwindow", "All"))
        self.label_7.setText(_translate("spyn_mainwindow", "  Energy"))
        self.btn_energy_GA_run.setText(_translate("spyn_mainwindow", "Calc"))
        self.btn_GA_run.setText(_translate("spyn_mainwindow", "Calc"))
        self.label_4.setText(_translate("spyn_mainwindow", "Log"))
        self.label_2.setText(_translate("spyn_mainwindow", "Conformers"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_CS_GA), _translate("spyn_mainwindow", "Genetic Algorithm"))
        self.tab_CS.setTabText(self.tab_CS.indexOf(self.tab), _translate("spyn_mainwindow", "Conformer Searching"))
        self.btn_automaticBoltz.setText(_translate("spyn_mainwindow", "OK"))
        self.txt_tempboltz.setText(_translate("spyn_mainwindow", "298.15"))
        self.lbl_tempboltz.setText(_translate("spyn_mainwindow", "                      Temperature (K):"))
        self.txt_nconfboltz.setText(_translate("spyn_mainwindow", "10"))
        self.cbox_unityboltz.setItemText(0, _translate("spyn_mainwindow", "kj/mol"))
        self.cbox_unityboltz.setItemText(1, _translate("spyn_mainwindow", "kcal/mol"))
        self.lbl_nconfboltz.setText(_translate("spyn_mainwindow", "                  Manual generation:"))
        self.ln_automaticboltz.setText(_translate("spyn_mainwindow", "10"))
        self.label_26.setText(_translate("spyn_mainwindow", "                                        Unity:"))
        self.label_27.setText(_translate("spyn_mainwindow", "              Automatic generation:"))
        self.btn_gerar_tables.setText(_translate("spyn_mainwindow", "OK"))
        self.btn_run_boltz.setText(_translate("spyn_mainwindow", "Run"))
        self.tab_CS.setTabText(self.tab_CS.indexOf(self.tab_2), _translate("spyn_mainwindow", "Boltzmann Distribution"))
        self.label_13.setText(_translate("spyn_mainwindow", "Acuraccy scf:"))
        self.label_14.setText(_translate("spyn_mainwindow", "          Generate input:"))
        self.label_28.setText(_translate("spyn_mainwindow", "    Filter gipaw output:"))
        self.chkbox_threadsnmr.setText(_translate("spyn_mainwindow", "Default"))
        self.ln_acuraccyscf.setText(_translate("spyn_mainwindow", "1.0D-10"))
        self.btn_pwout.setText(_translate("spyn_mainwindow", "OK"))
        self.ln_kgrid.setText(_translate("spyn_mainwindow", "222 111"))
        self.ln_stepscf.setText(_translate("spyn_mainwindow", "100"))
        self.label_5.setText(_translate("spyn_mainwindow", "           Kgrid:"))
        self.label_6.setText(_translate("spyn_mainwindow", "          Ibrave:"))
        self.cbox_filterscfout.setItemText(0, _translate("spyn_mainwindow", "Iterations"))
        self.cbox_filterscfout.setItemText(1, _translate("spyn_mainwindow", "Show all"))
        self.cbox_filterscfout.setItemText(2, _translate("spyn_mainwindow", "Total energy"))
        self.label_32.setText(_translate("spyn_mainwindow", "       Threads:"))
        self.ln_ibrav.setText(_translate("spyn_mainwindow", "0"))
        self.ln_cutoff.setText(_translate("spyn_mainwindow", "10"))
        self.label_16.setText(_translate("spyn_mainwindow", "       Calculate tensors:"))
        self.label_15.setText(_translate("spyn_mainwindow", "         Calculate PWscf:"))
        self.label_10.setText(_translate("spyn_mainwindow", "       Step scf:"))
        self.label_11.setText(_translate("spyn_mainwindow", "        (0-14)"))
        self.cbox_filtergipawout.setItemText(0, _translate("spyn_mainwindow", "C"))
        self.cbox_filtergipawout.setItemText(1, _translate("spyn_mainwindow", "H"))
        self.cbox_filtergipawout.setItemText(2, _translate("spyn_mainwindow", "P"))
        self.cbox_filtergipawout.setItemText(3, _translate("spyn_mainwindow", "N"))
        self.cbox_filtergipawout.setItemText(4, _translate("spyn_mainwindow", "O"))
        self.cbox_filtergipawout.setItemText(5, _translate("spyn_mainwindow", "Ag"))
        self.cbox_filtergipawout.setItemText(6, _translate("spyn_mainwindow", "S"))
        self.cbox_filtergipawout.setItemText(7, _translate("spyn_mainwindow", "Show all"))
        self.btn_pwin.setText(_translate("spyn_mainwindow", "OK"))
        self.ln_threadsnmr.setText(_translate("spyn_mainwindow", "4"))
        self.btn_gipaw.setText(_translate("spyn_mainwindow", "OK"))
        self.label_3.setText(_translate("spyn_mainwindow", "          Cutoff:"))
        self.label_25.setText(_translate("spyn_mainwindow", "         Filter scf output:"))
        self.label_22.setText(_translate("spyn_mainwindow", "              Optimize scf:"))
        self.btn_scfopt.setText(_translate("spyn_mainwindow", "OK"))
        self.ln_rangecutoff.setText(_translate("spyn_mainwindow", "10-100"))
        self.label_20.setText(_translate("spyn_mainwindow", "Cutoff\'s Range"))
        self.chk_kauto.setText(_translate("spyn_mainwindow", "Automatic"))
        self.label_9.setText(_translate("spyn_mainwindow", "  Diagonalization:"))
        self.cbox_pseudop.setItemText(1, _translate("spyn_mainwindow", "Ultrasoft"))
        self.label_8.setText(_translate("spyn_mainwindow", "Pseudo-Potential:"))
        self.cbox_diagonalization.setItemText(0, _translate("spyn_mainwindow", "David"))
        self.cbox_diagonalization.setItemText(1, _translate("spyn_mainwindow", "Cg"))
        self.label_12.setText(_translate("spyn_mainwindow", "               Nosym:"))
        self.cbox_nosym.setItemText(0, _translate("spyn_mainwindow", "True"))
        self.cbox_nosym.setItemText(1, _translate("spyn_mainwindow", "False"))
        self.txt_pwin.setHtml(_translate("spyn_mainwindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_19.setText(_translate("spyn_mainwindow", "Gipaw output:"))
        self.label_18.setText(_translate("spyn_mainwindow", "Output PWscf:"))
        self.label_17.setText(_translate("spyn_mainwindow", "Input PWscf:"))
        self.tab_CS.setTabText(self.tab_CS.indexOf(self.tab_ssnmr), _translate("spyn_mainwindow", "ss-NMR"))
        self.btn_nmrgraphGIPAW.setText(_translate("spyn_mainwindow", "Gipaw"))
        self.label_36.setText(_translate("spyn_mainwindow", "Theoretical:"))
        self.label_21.setText(_translate("spyn_mainwindow", "        PWscf:"))
        self.ln_tensors.setText(_translate("spyn_mainwindow", "2.42,2.89,4.51,4.68,7.00"))
        self.cbox_nmrgraphGIPAW.setItemText(0, _translate("spyn_mainwindow", "C"))
        self.cbox_nmrgraphGIPAW.setItemText(1, _translate("spyn_mainwindow", "H"))
        self.cbox_nmrgraphGIPAW.setItemText(2, _translate("spyn_mainwindow", "P"))
        self.cbox_nmrgraphGIPAW.setItemText(3, _translate("spyn_mainwindow", "N"))
        self.cbox_nmrgraphGIPAW.setItemText(4, _translate("spyn_mainwindow", "O"))
        self.cbox_nmrgraphGIPAW.setItemText(5, _translate("spyn_mainwindow", "Ag"))
        self.cbox_nmrgraphGIPAW.setItemText(6, _translate("spyn_mainwindow", "S"))
        self.btn_pwscfPLOT.setText(_translate("spyn_mainwindow", "OK"))
        self.btn_plotMANUAL.setText(_translate("spyn_mainwindow", "OK"))
        self.label_37.setText(_translate("spyn_mainwindow", "Manual:"))
        self.ln_reference.setText(_translate("spyn_mainwindow", "Reference"))
        self.btn_nmrgraphGIAO.setText(_translate("spyn_mainwindow", "Giao"))
        self.btn_resetPLOT.setText(_translate("spyn_mainwindow", "Reset"))
        self.ln_suavization.setText(_translate("spyn_mainwindow", "2"))
        self.label_39.setText(_translate("spyn_mainwindow", "Range y:"))
        self.ln_width.setText(_translate("spyn_mainwindow", "0.1"))
        self.ln_ymax.setText(_translate("spyn_mainwindow", "2"))
        self.label_38.setText(_translate("spyn_mainwindow", "Range x:"))
        self.ln_ymin.setText(_translate("spyn_mainwindow", "-0.1"))
        self.label_41.setText(_translate("spyn_mainwindow", "Width:"))
        self.label_43.setText(_translate("spyn_mainwindow", "Method:"))
        self.label_40.setText(_translate("spyn_mainwindow", "Intensity:"))
        self.ln_intensity.setText(_translate("spyn_mainwindow", "1"))
        self.label_42.setText(_translate("spyn_mainwindow", "Suavization:"))
        self.cbox_lorentzianSticks.setItemText(0, _translate("spyn_mainwindow", "Lorentzian"))
        self.cbox_lorentzianSticks.setItemText(1, _translate("spyn_mainwindow", "Sticks"))
        self.ln_xmin.setText(_translate("spyn_mainwindow", "0"))
        self.ln_xmax.setText(_translate("spyn_mainwindow", "10"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("spyn_mainwindow", "Tools"))
        self.tab_CS.setTabText(self.tab_CS.indexOf(self.tab_3), _translate("spyn_mainwindow", "Spectro-NMR"))
        self.menuFIle.setTitle(_translate("spyn_mainwindow", "File"))
        self.menuExport.setTitle(_translate("spyn_mainwindow", "Export"))
        self.menuConformers.setTitle(_translate("spyn_mainwindow", "Conformers"))
        self.menuGipaw.setTitle(_translate("spyn_mainwindow", "Gipaw"))
        self.menuPWscf.setTitle(_translate("spyn_mainwindow", "PWscf"))
        self.menuImport.setTitle(_translate("spyn_mainwindow", "Import"))
        self.menuNMR_exp.setTitle(_translate("spyn_mainwindow", "NMR exp"))
        self.menuCalc.setTitle(_translate("spyn_mainwindow", "Calc"))
        self.menuInput_Gaussian.setTitle(_translate("spyn_mainwindow", "Input Gaussian"))
        self.menuHelp.setTitle(_translate("spyn_mainwindow", "Help"))
        self.menuAbout.setTitle(_translate("spyn_mainwindow", "About"))
        self.menu_open.setText(_translate("spyn_mainwindow", "Open"))
        self.menu_open.setShortcut(_translate("spyn_mainwindow", "Ctrl+O"))
        self.menu_export_mol.setText(_translate("spyn_mainwindow", "as MOL"))
        self.menu_export_mol2.setText(_translate("spyn_mainwindow", "as MOL2"))
        self.menu_export_com.setText(_translate("spyn_mainwindow", "as COM"))
        self.menu_save.setText(_translate("spyn_mainwindow", "Save"))
        self.menu_save.setShortcut(_translate("spyn_mainwindow", "Ctrl+S"))
        self.menu_save_energy.setText(_translate("spyn_mainwindow", "Save Energy"))
        self.menu_save_conformers.setText(_translate("spyn_mainwindow", "Save Conformers"))
        self.menu_save_PWscf_input.setText(_translate("spyn_mainwindow", "Save PWscf input"))
        self.menu_save_PWscf_output.setText(_translate("spyn_mainwindow", "Save PWscf output"))
        self.menu_save_gipaw_input.setText(_translate("spyn_mainwindow", "Save Gipaw input"))
        self.menu_save_gipaw_output.setText(_translate("spyn_mainwindow", "Save Gipaw output"))
        self.menu_quit.setText(_translate("spyn_mainwindow", "Quit"))
        self.menu_quit.setShortcut(_translate("spyn_mainwindow", "Ctrl+Q"))
        self.menu_runCSGA.setText(_translate("spyn_mainwindow", "Run Conformer searching(GA)"))
        self.run_cs_ff.setText(_translate("spyn_mainwindow", "Run Conformer searching(FF)"))
        self.menu_runPWscf_input.setText(_translate("spyn_mainwindow", "Run Pwscf Input"))
        self.menu_runPWscf_output.setText(_translate("spyn_mainwindow", "Run Pwscf Output"))
        self.menu_runGipaw.setText(_translate("spyn_mainwindow", "Run Gipaw"))
        self.menu_tutorials.setText(_translate("spyn_mainwindow", "Tutorials"))
        self.menu_about.setText(_translate("spyn_mainwindow", "Atompy"))
        self.menu_giao.setText(_translate("spyn_mainwindow", "GIAO"))
        self.menu_optgiao.setText(_translate("spyn_mainwindow", "optGiao"))
        self.menu_ConformersOut.setText(_translate("spyn_mainwindow", "Conformers out"))
        self.menu_PWscfOut.setText(_translate("spyn_mainwindow", "PWscf out"))
        self.menu_GipawOut.setText(_translate("spyn_mainwindow", "Gipaw out"))
        self.menuExportConfs_sdf.setText(_translate("spyn_mainwindow", ".sdf"))
        self.menuExportConfs_mol.setText(_translate("spyn_mainwindow", ".mol"))
        self.menuExportEnergy.setText(_translate("spyn_mainwindow", "Energy"))
        self.menuExportGipaw_In.setText(_translate("spyn_mainwindow", "Input"))
        self.menuExportGipaw_Out.setText(_translate("spyn_mainwindow", "Output"))
        self.menuExportPWscf_In.setText(_translate("spyn_mainwindow", "Input"))
        self.menuExportPWscf_out.setText(_translate("spyn_mainwindow", "Output"))
        self.menu_nmrexpCSV.setText(_translate("spyn_mainwindow", "CSV"))
        self.menu_nmrexpBruker.setText(_translate("spyn_mainwindow", "Bruker ASC"))
        self.menu_Giaoout.setText(_translate("spyn_mainwindow", "Giao out"))
from mplwidget import MplWidget
